apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-aws-ebs-tagger.fullname" . }}
  labels:
    {{- include "k8s-aws-ebs-tagger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-aws-ebs-tagger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "k8s-aws-ebs-tagger.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-aws-ebs-tagger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - --lease-id=$(POD_NAME)
            - --lease-lock-namespace=$(NAMESPACE)
{{- if .Values.leaseLockName }}
            - --lease-lock-name={{ .Values.leaseLockName }}
{{- end }}
{{- if .Values.annotationPrefix }}
            - --annotation-prefix={{ .Values.annotationPrefix }}
{{- end }}
{{- if .Values.defaultTags }}
            - --default-tags={{ .Values.defaultTags | toJson }}
{{- end }}
{{- if .Values.watchNamespace }}
            - --watch-namespace={{ .Values.watchNamespace }}
{{- end }}
          env:
{{- if .Values.debug }}
            - name: DEBUG
              value: "true"
{{- end }}
            - name: AWS_REGION
              value: {{ .Values.region }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
